---

- name: install postgresql postgresql-contrib python3-pip libpq-dev (Debian)
  become_user: root
  apt:
    name:
    - postgresql
    - postgresql-contrib
    - python3-pip
    - libpq-dev
    state: latest
  when: ansible_facts['distribution_file_variety'] == "Debian"
- name: install postgresql postgresql-contrib python3-pip postgresql-libs (CentOS)
  become_user: root
  yum:
    name:
      - postgresql
      - postgresql-server
      - postgresql-contrib
      - python3-pip
      - postgresql-libs
      - python3-devel
      - postgresql-devel
    state: latest
  when: ansible_facts['distribution_file_variety'] == "CentOS"

- name: install pip psycopg2 patroni[etcd]
  become_user: root
  pip:
    name:
      - psycopg2
      - patroni[etcd]

- name: make /data/patroni directory
  file:
    path: /data/patroni
    state: directory
    mode: '0700'
    owner: postgres
    group: postgres
- name: patroni service and patroni.yml configs
  block:
    - name: etc/systemd/system/patroni.service config
      template:
        src: etc/systemd/system/patroni.service.j2
        dest: /etc/systemd/system/patroni.service
    - name: etc/patroni.yml config
      template:
        src: etc/patroni.yml.j2
        dest: /etc/patroni.yml
  notify: actions