---

- name: update repository index
  apt:
    update_cache: yes
- name: install etcd package
  apt:
    name: etcd
    state: latest
- name: etcd config
  block:
    - name: etcd configuration file
      template:
        src: etc/etcd
        dest: /etc/etcd2
    - name: etcd service configuration file
      template:
        src: etc/systemd/system/etcd.service
        dest: /etc/systemd/system/etcd.service2
  notify: restart daemon and etcd
- name: start etcd
  service:
    name: etcd
    state: started
  