---

- name: update repository index (Debian)
  apt:
    update_cache: yes
  when: ansible_facts['distribution_file_variety'] == "Debian"
- name: update repository index (CentOS)
  yum:
    update_cache: yes
  when: ansible_facts['distribution_file_variety'] == "CentOS"

- name: install etcd package
  apt:
    name: etcd
    state: latest
  when: ansible_facts['distribution_file_variety'] == "Debian"
  
- name: set etcd_release version variable (if CentOS)
  shell: curl -s https://api.github.com/repos/etcd-io/etcd/releases/latest|grep tag_name | cut -d '"' -f 4
  register: etcd_release
  when: ansible_facts['distribution_file_variety'] == "CentOS"
- name: Download file using etcd_release var (if CentOS)
  get_url:
    url: https://github.com/etcd-io/etcd/releases/download/{{ etcd_release.stdout }}/etcd-{{ etcd_release.stdout }}-linux-amd64.tar.gz
    dest: /home/maga/file.tar.gz
  when: ansible_facts['distribution_file_variety'] == "CentOS"
- name: unzip
  unarchive:
    src: /home/maga/file.tar.gz
    dest: /home/maga/testing
    remote_src: yes
  when: ansible_facts['distribution_file_variety'] == "CentOS"
- name: move binary files to /usr/local/bin/
  copy:
    src: /home/maga/testing/etcd-{{ etcd_release.stdout }}-linux-amd64/{{ item }}
    dest: /usr/local/bin/
    remote_src: yes
  loop:
    - etcd
    - etcdctl
    - etcdutl
  when: ansible_facts['distribution_file_variety'] == "CentOS"

- name: etcd config
  block:
    - name: etcd configuration file
      template:
        src: etc/etcd.j2
        dest: /etc/etcd
    - name: etcd service configuration file
      template:
        src: etc/systemd/system/etcd.service.Debian.j2
        dest: /etc/systemd/system/etcd.service
      when: ansible_facts['distribution_file_variety'] == "Debian"
    - name: etcd service configuration file
      template:
        src: etc/systemd/system/etcd.service.CentOS.j2
        dest: /etc/systemd/system/etcd.service
      when: ansible_facts['distribution_file_variety'] == "CentOS"
  notify: restart daemon and etcd
- name: start etcd
  service:
    name: etcd
    state: started



