---

- name: testing
  hosts: test
  tasks:

    - name: install postgresql postgresql-contrib python3-pip postgresql-libs
      become_user: root
      yum:
        name:
          - postgresql
          - postgresql-contrib
          - python3-pip
          - postgresql-libs
          - python3-devel
          - postgresql-devel
        state: latest
      when: ansible_facts['distribution_file_variety'] == "CentOS"
      
    - name: install pip psycopg2 patroni[etcd]
      become_user: root
      pip:
        name:
          - psycopg2
          - patroni[etcd]
      when: ansible_facts['distribution_file_variety'] == "CentOS"
    - name: uninstall old docker dependencies
      yum:
        name: 
          - docker
          - docker-client
          - docker-client-latest
          - docker-common
          - docker-latest
          - docker-latest-logrotate
          - docker-logrotate
          - docker-engine
        state: absent
    - name: install yum-utils
      yum:
        name: yum-utils
        state: latest
    - name: install docker repository
      shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
    - name: install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
      yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
      
