
---

- name: install keepalived
  yum:
    name: keepalived
    state: latest
    update_cache: yes
  when: ansible_facts['distribution_file_variety'] == "CentOS"
- name: Install the latest version of keepalived
  apt:
    name: keepalived
    state: latest
    update_cache: yes
  when: ansible_facts['distribution_file_variety'] == "Debian"
- name: /etc/keepalived/keepalived.conf file transfer
  template:
    src: etc/keepalived/keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
  notify: restart keepalived