---

- name: stop db
  service:
    name: postgresql
    enabled: yes
    state: stopped
  listen: actions
- name: restart patroni
  systemd_service:
    name: patroni
    state: started
  listen: actions
- name: restart db
  systemd_service:
    name: postgresql
    state: started
  listen: actions
- name: pause
  pause:
    seconds: 30
  when: mark == "host1"
  listen: actions