- name: Install aptitude
  apt:
    name: aptitude
    state: latest
    update_cache: true
  when: ansible_facts['distribution_file_variety'] == "Debian"
- name: uninstall old docker dependencies
  apt:
    name: 
      - docker.io
      - docker-doc
      - docker-compose
      - docker-compose-v2
      - podman-docker
      - containerd
    state: absent
  when: ansible_facts['distribution_file_variety'] == "Debian"
- name: update repository index
  apt:
    update_cache: yes
  when: ansible_facts['distribution_file_variety'] == "Debian"
- name: install ca-certificates curl gnupg
  apt:
    pkg:
    - ca-certificates
    - curl
    - apt-transport-https
    - software-properties-common
  when: ansible_facts['distribution_file_variety'] == "Debian"
- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  when: ansible_facts['distribution_file_variety'] == "Debian"
- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present
  when: ansible_facts['distribution_file_variety'] == "Debian"
- name: update repository index
  apt:
    update_cache: yes
  when: ansible_facts['distribution_file_variety'] == "Debian"
- name: install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
  apt:
    pkg:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin
  when: ansible_facts['distribution_file_variety'] == "Debian"


- name: uninstall old docker dependencies
  yum:
    name: 
      - docker
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - docker-engine
    state: absent
  when: ansible_facts['distribution_file_variety'] == "CentOS"
- name: install yum-utils
  yum:
    name: yum-utils
    state: latest
  when: ansible_facts['distribution_file_variety'] == "CentOS"
- name: install docker repository
  shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  when: ansible_facts['distribution_file_variety'] == "CentOS"
- name: install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
  yum:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
  when: ansible_facts['distribution_file_variety'] == "CentOS"

- name: Create /home/maga/Docker directory if doesn't exist
  file:
    path: /home/maga/Docker
    state: directory
- name: Copy files and create Docker image 
  block:
    - name: Dockerfile
      template:
        src: home/maga/Docker/Dockerfile
        dest: /home/maga/Docker/Dockerfile
    - name: etcd service configuration file
      template:
        src: home/maga/Docker/haproxy.cfg.j2
        dest: /home/maga/Docker/haproxy.cfg
  notify: restart container