---
# This Playbook will create PostgreSQL cluster with etcd, patroni and HAProxy

- hosts: all
  roles:
    - etcd

- hosts: all
  serial: 1
  roles:
    - db_patroni

- hosts: server1
  roles:
  - HAProxy